name: package_of_the_day
description: "100+ Flutter packages explored daily with hands-on examples, real-world use cases, and beginner-friendly implementations."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # --- Components & Indicators ---
  avatar_glow: ^3.0.1

  # For accessing all Google fonts
  google_fonts: ^8.2.0

  # For fancy pull to refresh
  liquid_pull_to_refresh: ^3.0.1

  # For percentage indicator
  percent_indicator: ^4.2.5

  # For Carousel Swipe
  flutter_carousel_slider: ^1.1.0

  # For cute & fun dot indicator
  smooth_page_indicator: ^2.0.1

  # For awesome icons
  font_awesome_flutter: ^11.0.0

  # For pre-built Animations
  animations: ^2.2.0

  # For Neon signs
  neon: ^0.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/


#  fonts:
#    - family: NeumorphicIcons
#      fonts:
#        - asset: assets/fonts/NeumorphicIcons.ttf