name: package_of_the_day
description: "100+ Flutter packages explored daily with hands-on examples, real-world use cases, and beginner-friendly implementations."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # --- Components & Indicators ---
  avatar_glow: ^3.0.1

  # For accessing all Google fonts
  google_fonts: ^8.2.0

  # For fancy pull to refresh
  liquid_pull_to_refresh: ^3.0.1

  # For percentage indicator
  percent_indicator: ^4.2.5

  # For Carousel Swipe
  flutter_carousel_slider: ^1.1.0

  # For cute & fun dot indicator
  smooth_page_indicator: ^2.0.1

  # For awesome icons
  font_awesome_flutter: ^11.0.0

  # For pre-built Animations
  animations: ^2.2.0

  # For Neon signs
  neon: ^0.1.0

  # For Aurora gradient
  aurora: ^1.0.0

  # For card swiping effects
  card_swiper: ^3.0.1

  # For displaying blur image while loading
  flutter_blurhash: ^0.9.1

  # For  rendering SVG image
  flutter_svg: ^2.3.0

  # For various custom shapes
  flutter_custom_clippers: ^2.1.0

  # For Text-to-speech in flutter
  flutter_tts: ^4.2.5

  # For Code highlight
  flutter_highlight: ^0.7.0

  # For Drawing charts
  syncfusion_flutter_charts: ^34.1.32

  # For displaying alert pop-up
  rflutter_alert: ^2.0.7

  # For setting ui for both android & iOS
  flutter_settings_ui: ^3.0.1

  # For animated loading indicators
  flutter_spinkit: ^5.2.2

  # For playing audio files
  audioplayers: ^6.7.1

  # For easy-to-use navigation
  go_router: ^17.3.0

  # For making HTTP request
  http: ^1.6.0

  # For landing page
  onboarding: ^4.0.2

  # For neumorphic UI design
  flutter_neumorphic_plus: ^3.5.0

  # For parsing and evaluating mathematical expressions
  math_expressions: ^3.1.0

  # For modern neumorphic containers
  clay_containers: ^0.3.4

  # For dark mode switch
  day_night_switch: ^1.0.4

  # For State-management
  provider: ^6.1.5+1

  # For using Lucide Icon pack
  flutter_lucide: ^1.11.0

  # For gradient text
  simple_gradient_text: ^1.4.0

  # For picking images from the image library, and taking new pictures with the camera
  image_picker: ^1.2.3

  # For Curved Labeled Navigation Bar
  curved_labeled_navigation_bar: ^2.0.6

  # For making a cool intro
  intro_slider: ^4.2.5

  # For icons
  phosphor_flutter: ^2.1.0

  # For advanced grid view
  flutter_staggered_grid_view: ^0.7.0

  # For shimmer loading effect
  shimmer: ^3.0.0

  # For animation
  lottie: ^3.3.3

  # For storing platform-specific persistent storage for simple data
  shared_preferences: ^2.5.5

  # For automatically resizes text to fit perfectly within its bounds
  auto_size_text_plus: ^3.0.2

  # For getting device information
  device_info_plus: ^13.2.0

  # For device geolocation
  geolocator: ^14.0.3

  # For GlassMorphism UI design
  glass_kit: ^4.0.2

  # For launching a URL
  url_launcher: ^6.3.2

  ## For loading and displaying html
  webview_flutter: ^4.14.1

  # For responsive UI design
  sizer: ^3.1.3

  # For playing video files
  video_player: ^2.11.1

  # For responsive design
  responsive_framework: ^1.5.1

  # For displaying timeline
  timelines_upgraded: ^0.1.1

  # For playing audio
  just_audio: ^0.10.6

  # Beautiful persistent bottom navigation
  persistent_bottom_nav_bar_v2: ^6.3.2

  # Value-based object comparison
  equatable: ^2.1.0

  # Config-based web scraper
  dart_web_scraper: ^0.2.16

  # For onboarding UI screen
  introduction_screen: ^4.0.0

  # For animated text
  animated_text_kit: ^4.3.0

  # For horizontal data table
  horizontal_data_table: ^4.3.4

  # For confetti animation
  confetti: ^0.8.0

  # Feature-rich video player
  chewie: ^1.14.1

  # Lightweight service locator
  get_it: ^9.2.1

  # Beautiful floating notifications
  another_flushbar: ^2.2.4

  # Network connectivity
  connectivity_plus: ^7.3.1

  # React Hooks for Flutter
  flutter_hooks: ^0.21.3+1

  # For locating the filesystem
  path_provider: ^2.1.6

  # For playing YouTube videos
  youtube_player_flutter: ^9.1.3

  # Official YouTube IFrame player
  youtube_player_iframe: ^6.0.2

  # For implementation of slidable list item
  flutter_slidable: ^4.0.3

  # For JSON to Dart class generator
  json_annotation: ^4.12.0

  # A powerful Http client for Dart
  dio: ^5.11.0

  # For saving images and videos in gallery
  gal: ^2.3.3

  # A customizable search field with auto-complete suggestions
  searchfield: ^2.0.0

  # Allows users to pick files from device storage with multiple format support
  file_picker: ^12.0.0-beta.7

  # For using the native APP to open files
  open_file: ^4.0.0

  # For sharing contents from Flutter app
  share_plus: ^13.3.0

  # For infinite scrolling
  infinite_scroll_pagination: ^5.1.1

  # For animated text
  marquee: ^2.3.0

  # For image caching & keeping them in cache directory
  cached_network_image: ^3.4.1

  # For managing network cached files
  flutter_cache_manager: ^3.4.2

  # For displaying toast messages
  fluttertoast: ^9.1.0

  # For cryptographic hashing functions
  crypto: ^3.0.7
  
  # For create animated countdown / countup timer
  slide_countdown: ^2.0.2

  # For formate date & time
  date_format: ^2.0.9

  # For custom rating bar
  custom_rating_bar: ^3.0.0

  # For OTP or pin code inputs
  pin_code_fields: ^9.4.0

  # For generating unique id
  uuid: ^4.6.0

  # For extending the capabilities of Dart Streams and StreamControllers
  rxdart: ^0.28.0

  # For local notifications
  flutter_local_notifications: ^22.3.0

  # For getting native device timezone of the os
  flutter_timezone: ^5.1.0

  # A library for Dart that generates fake data
  faker: ^2.2.0

  # A highly customizable and maintained bottom navigation bar
  stylish_bottom_bar: ^1.1.0

  # For previewing and testing UI responsiveness across various devices
  device_preview: ^1.3.1

  # For beautiful and high-performance UI animations
  animate_do: ^5.1.0

  # For modern, highly customizable and smooth animated toggles
  animated_toggle_switch: ^0.8.7

  # For advanced URL-based routing and deep-linking (Legacy)
  routemaster: ^1.1.1

  # For automatic skeleton loading states from existing widgets
  skeletonizer: ^2.1.3






dev_dependencies:
  # It provides a concrete way of generating files using Dart code
  build_runner: ^2.15.1
  # Dependency of "json_annotation"
  json_serializable: ^6.13.2



  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/videos/


#  fonts:
#    - family: NeumorphicIcons
#      fonts:
#        - asset: assets/fonts/NeumorphicIcons.ttf